Repository lblod/app-organization-portal, pull requests merged in 2022-10, with the labels that each got.

#177 fix order migration
  config/migrations/2022/20220930113653-fix-wrong-positions.sparql
  config/migrations/2022/20221004113653-create-missing-bedienaren-positions.sparql
Labels: bug

#179 Revert "Create and uniformize dates or organen before 2023"
  config/migrations/2022/20221004164323-uniformize-dates-or-organen-before-2023.sparql
Labels: enhancement

#182 remove bestrokken
  config/migrations/2022/20221007132340-delete-bestrokke.sparql
Labels: incident

#181 Create missing mandates for 2017 to 2023
  config/migrations/2022/20221004164323-uniformize-dates-or-organen-before-2023.sparql
  config/migrations/2022/20221005142834-create-missing-mandates-central-worship-organen-2020-2023.sparql
  config/migrations/2022/20221005142835-create-missing-mandates-central-worship-organen-2017-2020.sparql
  config/migrations/2022/20221005142836-create-missing-mandates-worship-organen-2017-2023.sparql
Labels: enhancement

#184 Fix/data from incidents
  config/migrations/2022/20221015110500-delete-kerkfabriek-st-baafs.sparql
  config/migrations/2022/20221015132000-delete-bestrokken-besturen-hemiksem.sparql
  config/migrations/2022/20221015134000-delete-bestrokken-besturen-ronse.sparql
Labels: incident
