Repository lblod/app-organization-portal, pull requests merged in 2023-12, with the labels that each got.

#356 Add publication triplestore and organizations public info producer
  config/delta-producer/dump-file-publisher/config.json
  config/delta-producer/organizations-public-info/export.json
  config/delta/rules.js
  config/dispatcher/dispatcher.ex
  config/jobs-controller/config.json
  config/publication-triplestore/virtuoso-production.ini
  config/publication-triplestore/virtuoso.ini
  docker-compose.dev.yml
  docker-compose.yml
Labels: enhancement

#357 Bump construct-administrative-unit-relationships-service
  docker-compose.yml
Labels: enhancement

#358 Fix/reasoner phone number rule
  config/reasoner/dl2op/main-info/phone_number.n3
  config/reasoner/dl2op/main/phone_number.n3
Labels: bug

#359 Fix: delete unnecessary change event
  config/migrations/2023/20231208160845-delete-change-event-lievegem.sparql
Labels: bug

#360 Import contact data from sharepoint
  config/migrations/2023/20231212101609-import-sharepoint-data/20231212101609-import-sharepoint-data-part-1.sparql
  config/migrations/2023/20231212101609-import-sharepoint-data/20231212101609-import-sharepoint-data-part-2.sparql
  config/migrations/2023/20231212101609-import-sharepoint-data/20231212101609-import-sharepoint-data-part-3.sparql
  config/migrations/2023/20231212101609-import-sharepoint-data/20231212101609-import-sharepoint-data-part-4.sparql
Labels: enhancement

#361 Add purpose and expected end date to producer
  config/delta-producer/organizations-public-info/export.json
Labels: enhancement

#362 Ignore publication triplestore data folder
  .gitignore
Labels: internal

#363 Add placeholder variables to prevent deltanotifier being slow
  docker-compose.yml
Labels: internal

#364 Replace https by http in lblodlg prefix
  config/migrations/2022/20220719112423-update-toezicht.sparql.disabled
  config/migrations/2022/20220819133740-delete-bestrokke-islam-orthodox.sparql
  config/migrations/2022/20220822133740-delete-bestrokke.sparql
  config/migrations/2022/20221007132340-delete-bestrokke.sparql
  config/migrations/2022/20221015132000-delete-bestrokken-besturen-hemiksem.sparql
  config/migrations/2022/20221015134000-delete-bestrokken-besturen-ronse.sparql
  config/migrations/2022/20221019174000-delete-bestrokken-besturen-anglican.sparql
  config/migrations/2022/20221222160000-fix-kbo-uris.sparql
  config/migrations/2023/20230616110000-street-and-bus-number-concatination.sparql
  config/migrations/2023/20230627110500-add-missing-country.sparql
  config/migrations/2023/20230627111000-add-country-to-full-address.sparql
  config/reports/utils.js
Labels: internal
