Repository lblod/app-organization-portal, pull requests merged in 2023-03, with the labels that each got.

#245 cache not triggered for related organization
  config/dispatcher/dispatcher.ex
Labels: bug

#249 fix orgaan wrong graph
  config/migrations/2023/20230306142222-move-orgaan-to-worship.sparql
Labels: bug

#251 Incident/move change event
  config/migrations/2023/20230227114600-remove-worship-not-actif.sparql
  config/migrations/2023/20230307091456-fix-wrong-resulting-org-after-merge.sparql
  config/search-migrations/2023/20230307100012-change-event-move.json
Labels: incident

#252 move kbo to worships
  config/migrations/2023/20230307125956-move-identifiers.sparql
Labels: bug

#254 Remove cache from dcat resources
  config/dispatcher/dispatcher.ex
Labels: bug

#253 fix privacy graph
  config/migrations/2023/20230228112800-hard-split/20230228132614-move-privacy-data.sparql
  config/migrations/2023/20230308112614-move-privacy-data.sparql
  config/migrations/2023/20230308112615-move-privacy-data-2.sparql
Labels: bug

#258 Fix status and add missing orgaan
  config/migrations-triggering-indexing/2023/20230324150743-update-status-and-orgaan-of-st-egidius-van-sint-gillis-waas.sparql
  docker-compose.yml
Labels: incident

#259 Enable new period for organen and create missing data
  config/migrations/2023/20230327162700-prepare-change-legislation-period/20230327162800-merge-organen.sparql
  config/migrations/2023/20230327162700-prepare-change-legislation-period/20230327162900-create-missing-organen-in-time-2023-2026.sparql
  config/migrations/2023/20230327162700-prepare-change-legislation-period/20230327163000-create-missing-positions-central-worship-services-2023-2026.sparql
  config/migrations/2023/20230327162700-prepare-change-legislation-period/20230327163000-create-missing-positions-worship-services-2023-2026.sparql
  docker-compose.yml
Labels: enhancement
