Repository lblod/app-organization-portal, pull requests merged in 2023-05, with the labels that each got.

#268 updating end date bestuursorgaan triggers too many deletes
  config/delta-producer/public/export.json
Labels: bug

#271 Ensure organen dates are datetimes
  config/migrations/2023/20230503143253-organen-start-and-end-should-be-datetimes-part-one.sparql
  config/migrations/2023/20230503143421-organen-start-and-end-should-be-datetimes-part-two.sparql
  config/resources/domain.json
Labels: bug

#273 Remove imported fracties and update reasoner config
  config/migrations/2023/20230504135910-delete-fracties-from-admin-unit-graph.sparql
  config/reasoner/dl2op/main-info/query.n3q
  config/reasoner/dl2op/main/query.n3q
Labels: bug

#272 Fix migration removing too much data
  config/migrations/2023/20230330164600-sync-loket-to-op/20230330164606-remove-ministers-that-will-get-synced.sparql
Labels: bug

#274 Remove deprecated delta-producer-json-diff-file-publisher service
  config/delta/rules.js
  config/dispatcher/dispatcher.ex
  docker-compose.dev.yml
  docker-compose.yml
Labels: internal

#269 Addition of ldes services to publish organization contact information
  .gitignore
  config/delta/rules.js
  config/dispatcher/dispatcher.ex
  config/ldes-delta-pusher/dispatch.ts
  config/migrations/2023/20230508093745-add-organization-type.sparql
  docker-compose.yml
Labels: enhancement

#280 Incident/adjust change event
  config/migrations/2023/20230522132503-adjust-change-event.sparql
Labels: incident

#279 Add dev profile to ldes feed
  config/delta/rules.js
  docker-compose.yml
Labels: internal

#255 Feat/onboarding agb apb
  config/migrations/2023/20230320135902-onboarding-agb-apb/20230321082905-public-triples.graph
  config/migrations/2023/20230320135902-onboarding-agb-apb/20230321082905-public-triples.ttl
  config/migrations/2023/20230320135902-onboarding-agb-apb/20230404101156-new-change-event.graph
  config/migrations/2023/20230320135902-onboarding-agb-apb/20230404101156-new-change-event.ttl
  config/pseudomize-migrations/20230420064420-pseudomize-data.sparql
Labels: enhancement
