Repository lblod/app-organization-portal, pull requests merged in 2023-09, with the labels that each got.

#323 Add migration to import igs address
  config/migrations/2023/20230704112900-onboarding-igs/20230907093015-import-igs-addresses.sparql
Labels: enhancement

#324 Fix duplicated primary sites
  config/migrations/2023/20230907133200-fix-double-primary-sites.sparql
  docker-compose.yml
Labels: bug

#325 Add missing restart statements
  docker-compose.yml
Labels: internal

#320 Add IGS related organizations
  config/migrations/2023/20230704112900-onboarding-igs/20230829164552-import-participants-links.sparql
Labels: enhancement

#326 Remove wrong classification from IGS IW
  config/migrations/2023/20230704112900-onboarding-igs/20230912112200-fix-igs-iw-classification.sparql
Labels: enhancement

#327 Import igs contact data
  config/migrations/2023/20230704112900-onboarding-igs/20230913102813-import-sharepoint-data.sparql
Labels: enhancement

#319 Add AGBs and APBs related organizations
  config/migrations/2023/20230320135902-onboarding-agb-apb/20230824150100-founding-members.sparql
Labels: enhancement

#328 Add related municipalities of IGS
  config/migrations/2023/20230704112900-onboarding-igs/20230913113222-related-municipalities.sparql
Labels: enhancement

#330 Onboarding PZ/HPZ - frontend compatibility changes
  config/migrations/2023/20230914154500-onboarding-pz-and-hpz/20230914154600-new-change-event.sparql
  docker-compose.yml
Labels: enhancement

#334 chore: bump mu-identifier
  docker-compose.yml
Labels: internal
