Repository lblod/app-organization-portal, pull requests merged in 2023-07, with the labels that each got.

#294 Add migration updating RO status
  config/migrations/2023/20230703181102-set-executief-van-de-moslims-van-belgie-to-not-active.sparql
Labels: incident

#296 Add migration importing existing IGS data from Loket
  config/migrations/2023/20230704112900-onboarding-igs/20230704112912-import-igs-from-loket.graph
  config/migrations/2023/20230704112900-onboarding-igs/20230704112912-import-igs-from-loket.ttl
Labels: enhancement

#295 Add new classification code for "Opdrachthoudende vereniging met private deelname"
  config/migrations/2023/20230704111900-add-opdrachthoudende-vereniging-met-private-deelname.graph
  config/migrations/2023/20230704111900-add-opdrachthoudende-vereniging-met-private-deelname.ttl
Labels: enhancement

#299 Update ldes-backend image to 0.3.3
  docker-compose.yml
Labels: internal

#305 Update ldes-backend image to 0.4.0
  docker-compose.dev.yml
  docker-compose.yml
Labels: internal

#300 Add IGS positions to the sync
  config/migrations/2023/20230712152618-igs-link-positions-to-unit-classifications.sparql
  config/reasoner/dl2op/main/query.n3q
  docker-compose.yml
Labels: enhancement

#302 Include local-identifier and label for each identifier of organizations sent to ldes feed
  config/ldes-delta-pusher/dispatch.ts
Labels: enhancement

#307 Import OVO codes for districts, worship and central worship services
  config/migrations/2023/20230720093300-add-district-ovos.sparql
  config/migrations/2023/20230720093301-add-worship-services-ovos.graph
  config/migrations/2023/20230720093301-add-worship-services-ovos.ttl
Labels: enhancement

#308 Variable name worship consumer
  config/loket-consumer/worship-services-sensitive-dispatching/delta-sync-dispatching.js
Labels: bug

#310 Import agb/apb addresses
  config/migrations/2023/20230718163900-add-agb-brugge.ttl
  config/migrations/2023/20230726100700-fix-agb-names.sparql
  config/migrations/2023/20230726123943-import-agb-addresses-2.sparql
  config/migrations/2023/20230726123943-import-agb-addresses.sparql
Labels: enhancement

#309 Remove torii redirect dispatching
  config/dev/tlsproxy/Caddyfile
  config/dispatcher/dispatcher.ex
Labels: internal

#312 Link admin units with OVO uris
  config/migrations/2023/20230728170200-add-link-between-uri-and-ovo-uri.sparql
Labels: enhancement
