Repository lblod/app-organization-portal, pull requests merged in 2024-04, with the labels that each got.

#400 Chore: bump mu-search version
  docker-compose.yml
Labels: internal

#401 chore: bumped consumers to latest version
  docker-compose.yml
Labels: internal

#375 Feat/wegwijs service integration
  config/authorization/config.ex
  config/dispatcher/dispatcher.ex
  config/resources/domain.json
  docker-compose.dev.yml
  docker-compose.yml
Labels: enhancement

#404 fix: remove empty alternative names for administrative units
  config/migrations/2024/20240403104506-remove-empty-alternative-names.sparql
Labels: bug

#405 Add execute permission on `scripts/reset-elastic.sh`
  scripts/reset-elastic.sh
Labels: internal

#407 Update adressenregister to use basisregisters adressen V2 API
  .gitignore
  config/dispatcher/dispatcher.ex
  config/migrations-sample/README.md
  config/migrations-sample/pseudonimyze-data.sparql-template
  config/migrations-sample/remove-stale-jobs.sparql-template
  config/migrations-sample/remove-type-in-producer-graph.sparql-template
  config/migrations/2023/20231205094344-mandaat-date-to-datetime.sparql
  config/migrations/2024/20240226102340-copy-name-to-legal-name.sparql
  config/migrations/2024/20240311134000-import-pz-hvz-names/20240311151100-delete-existing-alternative-names.sparql
  config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161908-import-politiezone-juridical-names.sparql
  config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161909-import-politiezone-alternative-names.sparql
  config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161910-import-hvz-juridical-names.sparql
  config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161911-import-hvz-alternative-names.sparql
  config/migrations/2024/20240318151601-fix-typo-boeddistiche-to-boeddistische.sparql
  config/migrations/local/.gitkeep
  config/migrations/local/README.md
  config/reasoner/dl2op/main-info/mapping.n3
  config/reasoner/dl2op/main/mapping.n3
  config/reasoner/dl2op/private-info/mapping.n3
  config/resources/domain.json
  config/search/config.json
  config/search/dev/config.json
  docker-compose.yml
Labels: bug

#408 feat: export legal and alternative names via producers
  config/delta-producer/organizations/export.json
  config/delta-producer/public/export.json
  config/delta-producer/worship-posts/export.json
Labels: enhancement

#412 Fix: correct type for classification to match resource configuration
  config/migrations/2024/20240415085335-correct-representative-body-classification-code-type.sparql
Labels: bug

#410 Improvement/update change event dates
  config/migrations/2024/20240408131200-update-change-event-dates.sparql
Labels: enhancement

#414 Fix consumer problem with admin units in shared graph
  config/clb-consumer/contact-data/delta-context-config.js
Labels: bug

#415 fix: add missing prefix
  config/reasoner/dl2op/private-info/mapping.n3
Labels: bug

#416 avoid inserting duplicate triples to the database
  config/clb-consumer/contact-data/delta-sync-dispatching.js
  config/clb-consumer/contact-data/util.js
Labels: enhancement

#419 fix/change-event-date-update-migration
  config/migrations/2024/20240408131200-update-change-event-dates.sparql
  config/migrations/2024/20240408131202-update-change-event-dates.sparql
Labels: bug
