Repository lblod/app-organization-portal, pull requests merged in 2024-05, with the labels that each got.

#420 fix: remove dangling change event results
  config/migrations/2024/20240429134438-remove-dangling-change-event-results.sparql
Labels: bug

#422 Fix kbo-data-sync rewrite all `fullAddress` and override `sameAs`
  config/dispatcher/dispatcher.ex
  docker-compose.yml
Labels: bug

#423 feat: import participants for public OCMW associations
  config/migrations/2024/20240517134134-public-ocmw-associations-related-organizations/20240517135033-ter-lembeek-import-participants.sparql
  config/migrations/2024/20240517134134-public-ocmw-associations-related-organizations/20240517154632-import-public-ocmw-association-participants.sparql
Labels: enhancement

#425 fix: exclude KBO organisations as participants
  config/dev-migrations/20240522095345-public-ocmw-associations-remov-participants.sparql
  config/migrations/2024/20240517134134-public-ocmw-associations-related-organizations/20240522120919-ter-lembeek-import-participants.sparql
  config/migrations/2024/20240517134134-public-ocmw-associations-related-organizations/20240522123045-import-public-ocmw-association-participants-part1.sparql
  config/migrations/2024/20240517134134-public-ocmw-associations-related-organizations/20240522123045-import-public-ocmw-association-participants-part2.sparql
Labels: bug

#427 Remove obsolete kbo-data-sync endpoint
  config/dispatcher/dispatcher.ex
Labels: internal
