Repository lblod/app-organization-portal, pull requests merged in 2024-01, with the labels that each got.

#367 Feature: onboarding public ocmw associations
  config/authorization/config.ex
  config/dev-migrations/20231222112146-add-ocmw-association-wieltjesgracht.sparql
  config/migrations/2023/20231129134822-onboarding-ocmw-verenigingen/20231129134823-autonome-verzorginginstelling.sparql
  config/migrations/2023/20231129134822-onboarding-ocmw-verenigingen/20231204120700-ziekenhuisvereniging.sparql
  config/migrations/2023/20231129134822-onboarding-ocmw-verenigingen/20231204120900-woonzorgvereniging-of-woonzorgvennootschap.sparql
  config/migrations/2023/20231129134822-onboarding-ocmw-verenigingen/20231204121000-vereniging-of-vennootschap-voor-sociale-dienstverlening.sparql
  config/reasoner/dl2op/main/query.n3q
  config/resources/domain.json
Labels: enhancement

#368 Feature: Added new classification codes for PEVAs
  config/migrations/2024/20240108134546-onboarding-peva/20240108134546-onboarding-peva-classification-code-peva-gemeente.sparql
  config/migrations/2024/20240108134546-onboarding-peva/20240108134610-onboarding-peva-classification-code-peva-provincie.sparql
  docker-compose.yml
Labels: enhancement

#369 fix missing resulting org & betrokke
  config/migrations/2024/20240115141651-fix-missing-resulting-orgs.sparql
Labels: bug, incident

#366 Bugt/fix duplicate lang strings
  config/migrations/2023/20231221132600-fix-duplicate-lang-strings.sparql
Labels: bug

#370 Feat/replace site type
  config/migrations/2024/20240117135900-replace-ander-administratief-adres-by-andere-vestiging.sparql
  config/migrations/2024/20240117145000-delete-ander-administratief-adres.sparql
Labels: enhancement

#371 add site type name attribute
  config/resources/domain.json
Labels: enhancement
