Repository lblod/app-organization-portal, pull requests merged in 2024-03, with the labels that each got.

#388 Fix: add missing bestuursfuncties for public OCMW associations
  config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240215140143-missing-organen-and-functies-for-ocmw-associations.sparql
  config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240305161100-import-missing-bestuursfuncties-loket.graph
  config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240305161100-import-missing-bestuursfuncties-loket.ttl
  config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240305180100-missing-organen-and-functies-for-ocmw-associations.sparql
  config/migrations/2024/20240214133210-onboarding-peva-data-import/20240215151234-create-governing-bodies-for-pevas.sparql
  config/migrations/2024/20240214133210-onboarding-peva-data-import/20240306101300-create-governing-bodies-for-pevas.sparql
Labels: bug

#389 fix: set correct value for provinces of OCMW associations and PEVAs
  config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240306133508-fix-ocmw-associations-provinces.sparql
  config/migrations/2024/20240214133210-onboarding-peva-data-import/20240306132750-fix-peva-provinces.sparql
Labels: bug

#387 Exclude the data of CLB from the producer
  config/delta-producer/organizations-public-info/export.json
Labels: enhancement

#395 Fix: reduce used resources by province fix migrations
  config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240306133508-fix-ocmw-associations-provinces.sparql
  config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240314103753-fix-ocmw-associations-provinces-part1.sparql
  config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240314103853-fix-ocmw-associations-provinces-part2.sparql
  config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240314103953-fix-ocmw-associations-provinces-part3.sparql
  config/migrations/2024/20240214133210-onboarding-peva-data-import/20240314095144-fix-peva-provinces.sparql
Labels: bug, internal

#392 Feature: Import juridical and alternative names for PZ and HVZ
  config/migrations/2024/20240311134000-import-pz-hvz-names/20240311151100-delete-existing-alternative-names.sparql
  config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161908-import-politiezone-juridical-names.sparql
  config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161909-import-politiezone-alternative-names.sparql
  config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161910-import-hvz-juridical-names.sparql
  config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161911-import-hvz-alternative-names.sparql
Labels: enhancement

#397 Adding 2 new recognized worship types
  config/migrations/2024/20240318142001-add-new-recognized-worship-types.sparql
  config/migrations/2024/20240318144801-update-missing-types-representative-bodies.sparql
Labels: bug

#396 Feature: add merge change event pz aalter maldegem
  config/migrations/2024/20240315104123-add-fusion-event-pz-aalter-maldegem.sparql
Labels: enhancement

#393 fix: remove superfluous local involvement
  config/migrations/2024/20240313141034-worship-Lochrist-remove-local-involvement.sparql
Labels: enhancement

#384 Chore: Add migration template samples
  .gitignore
  config/migrations-sample/README.md
  config/migrations-sample/pseudonimyze-data.sparql-template
  config/migrations-sample/remove-stale-jobs.sparql-template
  config/migrations-sample/remove-type-in-producer-graph.sparql-template
  config/migrations/local/.gitkeep
  config/migrations/local/README.md
Labels: internal
