Repository lblod/app-organization-portal, pull requests merged in 2025-01, with the labels that each got.

#490 Import 2025 NIS codes and update werkingsgebieden
  config/migrations/2025/20250107100000-nis-codes-2025/20250107101800-refnis2025.graph
  config/migrations/2025/20250107100000-nis-codes-2025/20250107101800-refnis2025.ttl
  config/migrations/2025/20250107100000-nis-codes-2025/20250107102500-add-uuids-to-nis-codes-2025.sparql
  config/migrations/2025/20250107100000-nis-codes-2025/20250107103200-update-nis-codes-to-2025-update.sparql
  config/migrations/2025/20250107100000-nis-codes-2025/20250107104100-link-new-fusie-gemeenten-to-their-nis-codes.sparql
Labels: enhancement

#494 fix: relate merged municipalities and province in shared graph
  config/migrations/2025/20250108143939-fix-municipality-mergers--move-province-hassuborganization-to-shared-graph.sparql
Labels: bug

#495 feat: merge police zones 2025
  config/migrations-triggering-indexing/2025/20250108194417-mergers-2025-police-zones--deactivate-merged-organisations.sparql
  config/migrations/2025/20250108184340-mergers-2025-police-zones/20250108184654-mergers-2025-police-zones--tongeren-borgloon-herstappe-heers-wellen.sparql
  config/migrations/2025/20250108184340-mergers-2025-police-zones/20250108190240-mergers-2025-police-zones--beveren_kruibeke_zwijndrecht-sint_gillis_waas-stekene-temse.sparql
  config/migrations/2025/20250108184340-mergers-2025-police-zones/20250108193811-mergers-2025-police-zones--vlaamse-ardennen.sparql
Labels: enhancement

#497 feat: allow local migrations that trigger indexing
  .gitignore
  config/migrations-triggering-indexing/local/.gitkeep
  config/migrations-triggering-indexing/local/README.md
Labels: internal

#502 Chore/update leidinggevenden consumer
  CHANGELOG.md
  README.md
  config/loket-consumer/leidinggevenden-dispatching/config.js
  config/loket-consumer/leidinggevenden-dispatching/delta-context-config.js
  config/loket-consumer/leidinggevenden-dispatching/delta-sync-dispatching.js
  config/loket-consumer/leidinggevenden-dispatching/initial-sync-dispatching.js
  config/loket-consumer/leidinggevenden-dispatching/util.js
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/data-cleanup/phone.rq
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/inheritance/Agent.rq
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/inheritance/AgentInPositie.rq
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/inverse/holds-to-held-by.rq
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/pass/address.sparql
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/pass/bestuursfunctie.sparql
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/pass/contactpoint.sparql
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/pass/functionaris.sparql
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/pass/person.sparql
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/predicate/person-foaf-name.sparql
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/predicate/person-gebruikte-voornaam.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113151927-flush-existing-leidinggevenden-data.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113151928-flush-existing-leidinggevenden-data.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113151929-flush-existing-leidinggevenden-data.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113151930-flush-existing-leidinggevenden-data.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113151931-flush-existing-leidinggevenden-data.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113151947-flush-landing-graph.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2023/20250113152654-flush-leidinggevenden-consumer-containers.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2023/20250113152655-flush-leidinggevenden-consumer-tasks.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2023/20250113152656-flush-leidinggevenden-consumer-jobs.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2024/20250113152657-flush-leidinggevenden-consumer-containers.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2024/20250113152658-flush-leidinggevenden-consumer-tasks.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2024/20250113152659-flush-leidinggevenden-consumer-jobs.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2025/20250113152660-flush-leidinggevenden-consumer-containers.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2025/20250113152661-flush-leidinggevenden-consumer-tasks.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2025/20250113152662-flush-leidinggevenden-consumer-jobs.sparql
  docker-compose.yml
Labels: enhancement

#509 refactor: clean up search indexing configurations
  config/search/config.json
  config/search/dev/config.json
  docker-compose.dev.yml
Labels: internal

#510 refactor: determine docker compose command based on system
  scripts/reset-elastic.sh
Labels: internal
