Repository lblod/app-organization-portal, pull requests merged in 2025-02, with the labels that each got.

#503 Bump worship consumer to v0.1.0
  CHANGELOG.md
  README.md
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/data-cleanup/phone.rq
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/date-to-datetime/contacthub-eindedatum.rq
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/date-to-datetime/contacthub-startdatum.rq
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/date-to-datetime/ere-geplande-einddatum-aanstelling.rq
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/inheritance/Agent.rq
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/inheritance/AgentInPositie.rq
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/inverse/held-by-to-holds.rq
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/inverse/holds-to-held-by.rq
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/pass/address.sparql
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/pass/bestuursfunctie.sparql
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/pass/contactpoint.sparql
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/pass/eredienst-mandataris.sparql
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/pass/person.sparql
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/pass/rol-bedienaar.sparql
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/predicate/gebruikte-voornaam.rq
  config/loket-consumer/worship-services-main-info/mapping/queries/dl2op/predicate/given-name.rq
  config/loket-consumer/worship-services-private-info/mapping/queries/dl2op/pass/geboorte.sparql
  config/loket-consumer/worship-services-private-info/mapping/queries/dl2op/persoon-http-to-https/Geboorte.rq
  config/loket-consumer/worship-services-private-info/mapping/queries/dl2op/persoon-http-to-https/datum.rq
  config/loket-consumer/worship-services-private-info/mapping/queries/dl2op/persoon-http-to-https/geslacht.rq
  config/loket-consumer/worship-services-private-info/mapping/queries/dl2op/persoon-http-to-https/heeftGeboorte.rq
  config/loket-consumer/worship-services-private-info/mapping/queries/dl2op/persoon-http-to-https/heeftNationaliteit.rq
  config/loket-consumer/worship-services-private-info/mapping/queries/dl2op/persoon-http-to-https/registratie.rq
  config/loket-consumer/worship-services-private-info/mapping/queries/dl2op/rrn/identifier.rq
  config/loket-consumer/worship-services-private-info/mapping/queries/dl2op/rrn/registratie.rq
  config/loket-consumer/worship-services-sensitive-dispatching/config.js
  config/loket-consumer/worship-services-sensitive-dispatching/delta-context-config.js
  config/loket-consumer/worship-services-sensitive-dispatching/delta-sync-dispatching.js
  config/loket-consumer/worship-services-sensitive-dispatching/initial-sync-dispatching.js
  config/loket-consumer/worship-services-sensitive-dispatching/util.js
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2023/20250115095500-flush-eredienst-mandatarissen-consumer-containers.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2023/20250115095600-flush-eredienst-mandatarissen-consumer-tasks.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2023/20250115095700-flush-eredienst-mandatarissen-consumer-jobs.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2024/20250115095800-flush-eredienst-mandatarissen-consumer-containers.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2024/20250115095900-flush-eredienst-mandatarissen-consumer-tasks.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2024/20250115096000-flush-eredienst-mandatarissen-consumer-jobs.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2025/20250115096100-flush-eredienst-mandatarissen-consumer-containers.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2025/20250115096200-flush-eredienst-mandatarissen-consumer-tasks.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2025/20250115096300-flush-eredienst-mandatarissen-consumer-jobs.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250116085100-remove-loket-persons-birthdates.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250116085200-remove-loket-persons-identifiers.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250116085300-remove-loket-persons.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250116085400-contact-points.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250116085600-remove-agents-in-position.sparql
  config/migrations/2025/20250116085000-sync-from-loket-consumers-bump/20250116134600-flush-landing-zone.sparql
  docker-compose.dev.yml
  docker-compose.yml
Labels: enhancement

#512 Add dates mapping rules for mandatarissen and leidinggevenden consumers
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/datetime-format/mandaat-einde.rq
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/datetime-format/mandaat-start.rq
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/inheritance/Agent.rq
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/inheritance/AgentInPositie.rq
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/pass/address.sparql
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/pass/bestuursfunctie.sparql
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/pass/contactpoint.sparql
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/pass/functionaris.sparql
  config/loket-consumer/leidinggevenden/mapping/queries/dl2op/pass/person.sparql
  config/loket-consumer/mandatarissen/mapping/queries/dl2op/datetime-format/mandaat-einde.rq
  config/loket-consumer/mandatarissen/mapping/queries/dl2op/datetime-format/mandaat-start.rq
  config/loket-consumer/mandatarissen/mapping/queries/dl2op/pass/mandataris.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2023/20250113153654-flush-leidinggevenden-consumer-containers.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2023/20250113153655-flush-leidinggevenden-consumer-tasks.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2023/20250113153656-flush-leidinggevenden-consumer-jobs.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2024/20250113153657-flush-leidinggevenden-consumer-containers.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2024/20250113153658-flush-leidinggevenden-consumer-tasks.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2024/20250113153659-flush-leidinggevenden-consumer-jobs.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2025/20250113153660-flush-leidinggevenden-consumer-containers.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2025/20250113153661-flush-leidinggevenden-consumer-tasks.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152654-flush-old-jobs/2025/20250113153662-flush-leidinggevenden-consumer-jobs.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152927-flush-existing-leidinggevenden-data.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152928-flush-existing-leidinggevenden-data.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152929-flush-existing-leidinggevenden-data.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152930-flush-existing-leidinggevenden-data.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152931-flush-existing-leidinggevenden-data.sparql
  config/migrations/2025/20250113000000-update-leidinggevenden-consumer/20250113152947-flush-landing-graph.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2023/20250115095500-flush-eredienst-mandatarissen-consumer-containers.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2023/20250115095600-flush-eredienst-mandatarissen-consumer-tasks.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2023/20250115095700-flush-eredienst-mandatarissen-consumer-jobs.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2024/20250115095800-flush-eredienst-mandatarissen-consumer-containers.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2024/20250115095900-flush-eredienst-mandatarissen-consumer-tasks.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2024/20250115096000-flush-eredienst-mandatarissen-consumer-jobs.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2025/20250115096100-flush-eredienst-mandatarissen-consumer-containers.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2025/20250115096200-flush-eredienst-mandatarissen-consumer-tasks.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250115095500-flush-eredienst-mandatarissen-consumer-jobs/2025/20250115096300-flush-eredienst-mandatarissen-consumer-jobs.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250116085100-remove-loket-persons-birthdates.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250116085200-remove-loket-persons-identifiers.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250116085300-remove-loket-persons.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250116085400-contact-points.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250116085600-remove-agents-in-position.sparql
  config/migrations/2025/20250116085000-update-worship-consumer/20250116134600-flush-landing-zone.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122204101-flush-old-jobs/2023/20250122304102-flush-mandatarissen-consumer-containers.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122204101-flush-old-jobs/2023/20250122304103-flush-mandatarissen-consumer-tasks.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122204101-flush-old-jobs/2023/20250122304104-flush-mandatarissen-consumer-jobs.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122204101-flush-old-jobs/2024/20250122304105-flush-mandatarissen-consumer-containers.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122204101-flush-old-jobs/2024/20250122304106-flush-mandatarissen-consumer-tasks.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122204101-flush-old-jobs/2024/20250122304107-flush-mandatarissen-consumer-jobs.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122204101-flush-old-jobs/2025/20250122304108-flush-mandatarissen-consumer-containers.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122204101-flush-old-jobs/2025/20250122304109-flush-mandatarissen-consumer-tasks.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122204101-flush-old-jobs/2025/20250122304110-flush-mandatarissen-consumer-jobs.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122304111-flush-existing-mandatarissen-data.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122304112-flush-existing-mandatarissen-data.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122304113-flush-existing-mandatarissen-data.sparql
  config/migrations/2025/20250122204100-update-mandatarissen-consumer/20250122304114-flush-landing-graph.sparql
Labels: bug

#514 chore: additional example environment settings for worship consumers
  docker-compose.yml
Labels: internal

#513 Remove reasoner service, replaced by new consumer logic
  CHANGELOG.md
  config/reasoner/dl2op/main-info/inverse_relations.n3
  config/reasoner/dl2op/main-info/mapping.n3
  config/reasoner/dl2op/main-info/persoon_http_to_https.n3
  config/reasoner/dl2op/main-info/phone_number.n3
  config/reasoner/dl2op/main-info/query.n3q
  config/reasoner/dl2op/main-info/retract_empty_strings.n3
  config/reasoner/dl2op/main-info/rrn.n3
  config/reasoner/dl2op/main/inverse_relations.n3
  config/reasoner/dl2op/main/mapping.n3
  config/reasoner/dl2op/main/persoon_http_to_https.n3
  config/reasoner/dl2op/main/phone_number.n3
  config/reasoner/dl2op/main/query.n3q
  config/reasoner/dl2op/main/retract_empty_strings.n3
  config/reasoner/dl2op/main/rrn.n3
  config/reasoner/dl2op/private-info/inverse_relations.n3
  config/reasoner/dl2op/private-info/mapping.n3
  config/reasoner/dl2op/private-info/persoon_http_to_https.n3
  config/reasoner/dl2op/private-info/query.n3q
  config/reasoner/dl2op/private-info/retract_empty_strings.n3
  config/reasoner/dl2op/private-info/rrn.n3
  docker-compose.yml
Labels: internal

#519 chore: move status for municipalities and provinces in shared graph
  CHANGELOG.md
  config/migrations/2025/20250220171921-move-status-for-municipalities-and-provinces-to-shared-graph.sparql
Labels: enhancement
